- project-template:
    name: networking-ansible-tempest-jobs
    check:
      jobs:
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode-networking-ansible:
            voting: false
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-networking-ansible
    gate:
      jobs:
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode-networking-ansible:
            voting: false
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-networking-ansible

- project:
    templates:
      - networking-ansible-tempest-jobs
      - openstack-cover-jobs
      - openstack-python3-ussuri-jobs
      - periodic-jobs-with-neutron-lib-master
      - check-requirements
      - docs-on-readthedocs
    vars:
      rtd_webhook_id: '45496'
